apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodcataloguepracapp
  labels:
    app: foodcataloguepracapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodcataloguepracapp
  template:
    metadata:
      labels:
        app: foodcataloguepracapp
    spec:
      containers:
        - name: foodcataloguepracapp
          image: hsenidbhu/food-catalogue-prac:0.0.22
          imagePullPolicy: Always
          ports:
            - containerPort: 9093
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: foodcataloguedb_url
---
apiVersion: v1
kind: Service
metadata:
  name: foodcatalogueprac-service
spec:
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  selector:
    app: foodcataloguepracapp
 
