apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
  labels:
    app: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: hsenidbhu/restaurant-listing-service:0.0.12
          imagePullPolicy: Always
          ports:
            - containerPort: 9095
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: restaurantdb_url
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant2-service
spec:
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
  selector:
    app: restaurant
 
